export const GET_PRODUCTS_BEGIN='GET_PRODUCTS_BEGIN';
export const GET_PRODUCTS_SUCCESS='GET_PRODUCTS_SUCCESS';
export const GET_PRODUCTS_FAIL='GET_PRODUCTS_FAIL';

export const SEARCH_BEGIN='SEARCH_BEGIN';
export const SEARCH_SUCCESS='SEARCH_SUCCESS';
export const SEARCH_FAIL='SEARCH_FAIL';

export const APPLY_FILTER_BEGIN='APPLY_FILTER_BEGIN';
export const APPLY_FILTER_SUCCESS='APPLY_FILTER_SUCCESS';
export const APPLY_FILTER_FAIL='APPLY_FILTER_FAIL';
